FROM php:8.3-fpm

# Update OS repositories
RUN apt-get update --yes

# Install essential packages
RUN apt-get install --yes \
    autoconf \
    bzip2 \
    curl \
    gettext \
    git \
    g++ \
    make \
    libbz2-dev \
    libicu-dev \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    libtidy-dev \
    libxslt-dev \
    tar \
    unzip \
    zlib1g-dev \
    iputils-ping \
    zip \
    libzip-dev \
    default-mysql-client

# Install PHP extensions
RUN docker-php-ext-install bcmath \
    bz2 \
    calendar \
    exif \
    gd \
    gettext \
    intl \
    pcntl \
    mysqli \
    pdo pdo_mysql \
    xsl \
    zip

# Enable extensions
RUN docker-php-ext-enable zip gd pdo_mysql pdo intl

# Configure GD
RUN docker-php-ext-configure gd --with-freetype=/usr/include/ --with-jpeg=/usr/include/

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Install XDebug
RUN pecl install xdebug
RUN docker-php-ext-enable xdebug

# Configure Xdebug
RUN echo "xdebug.mode=debug" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
RUN echo "xdebug.client_host=host.docker.internal" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
RUN echo "xdebug.client_port=9003" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
RUN echo "xdebug.start_with_request=yes" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

# Install Node.js
RUN curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
RUN apt-get install -y nodejs

# Clean up
RUN apt-get clean -y
RUN rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*

# Set working directory
WORKDIR /var/www

# RUN php artisan cache:clear
# RUN chmod -R 775 storage
# RUN composer install --optimize-autoloader --no-dev